ALTER TABLE "Campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignLead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CampaignSeenCompany" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Contact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyQuota" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DiscoverySeenCompany" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Email" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Template" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserLead" ENABLE ROW LEVEL SECURITY;

